// Code generated by MockGen. DO NOT EDIT.
// Source: services/v1/service/srv.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "be-cadidate-votes/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateCandidate mocks base method.
func (m *MockService) CreateCandidate(ctx context.Context, req models.CreateCandidateRequest) (models.CreateCandidateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCandidate", ctx, req)
	ret0, _ := ret[0].(models.CreateCandidateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCandidate indicates an expected call of CreateCandidate.
func (mr *MockServiceMockRecorder) CreateCandidate(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCandidate", reflect.TypeOf((*MockService)(nil).CreateCandidate), ctx, req)
}

// DeleteCandidate mocks base method.
func (m *MockService) DeleteCandidate(ctx context.Context, req models.ListCandidateRequest) (models.CreateCandidateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCandidate", ctx, req)
	ret0, _ := ret[0].(models.CreateCandidateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCandidate indicates an expected call of DeleteCandidate.
func (mr *MockServiceMockRecorder) DeleteCandidate(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCandidate", reflect.TypeOf((*MockService)(nil).DeleteCandidate), ctx, req)
}

// ListCandidate mocks base method.
func (m *MockService) ListCandidate(ctx context.Context, req models.ListCandidateRequest) (models.ListCandidateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCandidate", ctx, req)
	ret0, _ := ret[0].(models.ListCandidateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCandidate indicates an expected call of ListCandidate.
func (mr *MockServiceMockRecorder) ListCandidate(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCandidate", reflect.TypeOf((*MockService)(nil).ListCandidate), ctx, req)
}

// Login mocks base method.
func (m *MockService) Login(ctx context.Context, req models.RegisterUserRequest) (models.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(models.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockServiceMockRecorder) Login(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockService)(nil).Login), ctx, req)
}

// RegisterUser mocks base method.
func (m *MockService) RegisterUser(ctx context.Context, req models.RegisterUserRequest) (models.RegisterUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, req)
	ret0, _ := ret[0].(models.RegisterUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockServiceMockRecorder) RegisterUser(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockService)(nil).RegisterUser), ctx, req)
}

// UpdateCandidate mocks base method.
func (m *MockService) UpdateCandidate(ctx context.Context, req models.UpdateCandidateRequest) (models.CreateCandidateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCandidate", ctx, req)
	ret0, _ := ret[0].(models.CreateCandidateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCandidate indicates an expected call of UpdateCandidate.
func (mr *MockServiceMockRecorder) UpdateCandidate(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCandidate", reflect.TypeOf((*MockService)(nil).UpdateCandidate), ctx, req)
}
